<?php

namespace Database\Seeders;

use App\Admin\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        District::truncate();
        District::create(['id' => '1','name' => "Quận Ba Đình",'city_id' =>1]);
        District::create(['id' => '2','name' => "Quận Hoàn Kiếm",'city_id' =>1]);
        District::create(['id' => '3','name' => "Quận Tây Hồ",'city_id' =>1]);
        District::create(['id' => '4','name' => "Quận Long Biên",'city_id' =>1]);
        District::create(['id' => '5','name' => "Quận Cầu Giấy",'city_id' =>1]);
        District::create(['id' => '6','name' => "Quận Đống Đa",'city_id' =>1]);
        District::create(['id' => '7','name' => "Quận Hai Bà Trưng",'city_id' =>1]);
        District::create(['id' => '8','name' => "Quận Hoàng Mai",'city_id' =>1]);
        District::create(['id' => '9','name' => "Quận Thanh Xuân",'city_id' =>1]);
        District::create(['id' => '10','name' => "Huyện Sóc Sơn",'city_id' =>1]);
        District::create(['id' => '11','name' => "Huyện Đông Anh",'city_id' =>1]);
        District::create(['id' => '12','name' => "Huyện Gia Lâm",'city_id' =>1]);
        District::create(['id' => '13','name' => "Quận Nam Từ Liêm",'city_id' =>1]);
        District::create(['id' => '14','name' => "Huyện Thanh Trì",'city_id' =>1]);
        District::create(['id' => '15','name' => "Quận Bắc Từ Liêm",'city_id' =>1]);
        District::create(['id' => '16','name' => "Thành phố Hà Giang",'city_id' =>2]);
        District::create(['id' => '17','name' => "Huyện Đồng Văn",'city_id' =>2]);
        District::create(['id' => '18','name' => "Huyện Mèo Vạc",'city_id' =>2]);
        District::create(['id' => '19','name' => "Huyện Yên Minh",'city_id' =>2]);
        District::create(['id' => '20','name' => "Huyện Quản Bạ",'city_id' =>2]);
        District::create(['id' => '21','name' => "Huyện Vị Xuyên",'city_id' =>2]);
        District::create(['id' => '22','name' => "Huyện Bắc Mê",'city_id' =>2]);
        District::create(['id' => '23','name' => "Huyện Hoàng Su Phì",'city_id' =>2]);
        District::create(['id' => '24','name' => "Huyện Xín Mần",'city_id' =>2]);
        District::create(['id' => '25','name' => "Huyện Bắc Quang",'city_id' =>2]);
        District::create(['id' => '26','name' => "Huyện Quang Bình",'city_id' =>2]);
        District::create(['id' => '27','name' => "Thành phố Cao Bằng",'city_id' =>4]);
        District::create(['id' => '28','name' => "Huyện Bảo Lâm",'city_id' =>4]);
        District::create(['id' => '29','name' => "Huyện Bảo Lạc",'city_id' =>4]);
        District::create(['id' => '30','name' => "Huyện Hà Quảng",'city_id' =>4]);
        District::create(['id' => '31','name' => "Huyện Trùng Khánh",'city_id' =>4]);
        District::create(['id' => '32','name' => "Huyện Hạ Lang",'city_id' =>4]);
        District::create(['id' => '33','name' => "Huyện Quảng Hòa",'city_id' =>4]);
        District::create(['id' => '34','name' => "Huyện Hoà An",'city_id' =>4]);
        District::create(['id' => '35','name' => "Huyện Nguyên Bình",'city_id' =>4]);
        District::create(['id' => '36','name' => "Huyện Thạch An",'city_id' =>4]);
        District::create(['id' => '37','name' => "Thành Phố Bắc Kạn",'city_id' =>6]);
        District::create(['id' => '38','name' => "Huyện Pác Nặm",'city_id' =>6]);
        District::create(['id' => '39','name' => "Huyện Ba Bể",'city_id' =>6]);
        District::create(['id' => '40','name' => "Huyện Ngân Sơn",'city_id' =>6]);
        District::create(['id' => '41','name' => "Huyện Bạch Thông",'city_id' =>6]);
        District::create(['id' => '42','name' => "Huyện Chợ Đồn",'city_id' =>6]);
        District::create(['id' => '43','name' => "Huyện Chợ Mới",'city_id' =>6]);
        District::create(['id' => '44','name' => "Huyện Na Rì",'city_id' =>6]);
        District::create(['id' => '45','name' => "Thành phố Tuyên Quang",'city_id' =>8]);
        District::create(['id' => '46','name' => "Huyện Lâm Bình",'city_id' =>8]);
        District::create(['id' => '47','name' => "Huyện Na Hang",'city_id' =>8]);
        District::create(['id' => '48','name' => "Huyện Chiêm Hóa",'city_id' =>8]);
        District::create(['id' => '49','name' => "Huyện Hàm Yên",'city_id' =>8]);
        District::create(['id' => '50','name' => "Huyện Yên Sơn",'city_id' =>8]);
        District::create(['id' => '51','name' => "Huyện Sơn Dương",'city_id' =>8]);
        District::create(['id' => '52','name' => "Thành phố Lào Cai",'city_id' =>10]);
        District::create(['id' => '53','name' => "Huyện Bát Xát",'city_id' =>10]);
        District::create(['id' => '54','name' => "Huyện Mường Khương",'city_id' =>10]);
        District::create(['id' => '55','name' => "Huyện Si Ma Cai",'city_id' =>10]);
        District::create(['id' => '56','name' => "Huyện Bắc Hà",'city_id' =>10]);
        District::create(['id' => '57','name' => "Huyện Bảo Thắng",'city_id' =>10]);
        District::create(['id' => '58','name' => "Huyện Bảo Yên",'city_id' =>10]);
        District::create(['id' => '59','name' => "Thị xã Sa Pa",'city_id' =>10]);
        District::create(['id' => '60','name' => "Huyện Văn Bàn",'city_id' =>10]);
        District::create(['id' => '61','name' => "Thành phố Điện Biên Phủ",'city_id' =>11]);
        District::create(['id' => '62','name' => "Thị Xã Mường Lay",'city_id' =>11]);
        District::create(['id' => '63','name' => "Huyện Mường Nhé",'city_id' =>11]);
        District::create(['id' => '64','name' => "Huyện Mường Chà",'city_id' =>11]);
        District::create(['id' => '65','name' => "Huyện Tủa Chùa",'city_id' =>11]);
        District::create(['id' => '66','name' => "Huyện Tuần Giáo",'city_id' =>11]);
        District::create(['id' => '67','name' => "Huyện Điện Biên",'city_id' =>11]);
        District::create(['id' => '68','name' => "Huyện Điện Biên Đông",'city_id' =>11]);
        District::create(['id' => '69','name' => "Huyện Mường Ảng",'city_id' =>11]);
        District::create(['id' => '70','name' => "Huyện Nậm Pồ",'city_id' =>11]);
        District::create(['id' => '71','name' => "Thành phố Lai Châu",'city_id' =>12]);
        District::create(['id' => '72','name' => "Huyện Tam Đường",'city_id' =>12]);
        District::create(['id' => '73','name' => "Huyện Mường Tè",'city_id' =>12]);
        District::create(['id' => '74','name' => "Huyện Sìn Hồ",'city_id' =>12]);
        District::create(['id' => '75','name' => "Huyện Phong Thổ",'city_id' =>12]);
        District::create(['id' => '76','name' => "Huyện Than Uyên",'city_id' =>12]);
        District::create(['id' => '77','name' => "Huyện Tân Uyên",'city_id' =>12]);
        District::create(['id' => '78','name' => "Huyện Nậm Nhùn",'city_id' =>12]);
        District::create(['id' => '79','name' => "Thành phố Sơn La",'city_id' =>14]);
        District::create(['id' => '80','name' => "Huyện Quỳnh Nhai",'city_id' =>14]);
        District::create(['id' => '81','name' => "Huyện Thuận Châu",'city_id' =>14]);
        District::create(['id' => '82','name' => "Huyện Mường La",'city_id' =>14]);
        District::create(['id' => '83','name' => "Huyện Bắc Yên",'city_id' =>14]);
        District::create(['id' => '84','name' => "Huyện Phù Yên",'city_id' =>14]);
        District::create(['id' => '85','name' => "Huyện Mộc Châu",'city_id' =>14]);
        District::create(['id' => '86','name' => "Huyện Yên Châu",'city_id' =>14]);
        District::create(['id' => '87','name' => "Huyện Mai Sơn",'city_id' =>14]);
        District::create(['id' => '88','name' => "Huyện Sông Mã",'city_id' =>14]);
        District::create(['id' => '89','name' => "Huyện Sốp Cộp",'city_id' =>14]);
        District::create(['id' => '90','name' => "Huyện Vân Hồ",'city_id' =>14]);
        District::create(['id' => '91','name' => "Thành phố Yên Bái",'city_id' =>15]);
        District::create(['id' => '92','name' => "Thị xã Nghĩa Lộ",'city_id' =>15]);
        District::create(['id' => '93','name' => "Huyện Lục Yên",'city_id' =>15]);
        District::create(['id' => '94','name' => "Huyện Văn Yên",'city_id' =>15]);
        District::create(['id' => '95','name' => "Huyện Mù Căng Chải",'city_id' =>15]);
        District::create(['id' => '96','name' => "Huyện Trấn Yên",'city_id' =>15]);
        District::create(['id' => '97','name' => "Huyện Trạm Tấu",'city_id' =>15]);
        District::create(['id' => '98','name' => "Huyện Văn Chấn",'city_id' =>15]);
        District::create(['id' => '99','name' => "Huyện Yên Bình",'city_id' =>15]);
        District::create(['id' => '100','name' => "Thành phố Hòa Bình",'city_id' =>17]);
        District::create(['id' => '101','name' => "Huyện Đà Bắc",'city_id' =>17]);
        District::create(['id' => '102','name' => "Huyện Lương Sơn",'city_id' =>17]);
        District::create(['id' => '103','name' => "Huyện Kim Bôi",'city_id' =>17]);
        District::create(['id' => '104','name' => "Huyện Cao Phong",'city_id' =>17]);
        District::create(['id' => '105','name' => "Huyện Tân Lạc",'city_id' =>17]);
        District::create(['id' => '106','name' => "Huyện Mai Châu",'city_id' =>17]);
        District::create(['id' => '107','name' => "Huyện Lạc Sơn",'city_id' =>17]);
        District::create(['id' => '108','name' => "Huyện Yên Thủy",'city_id' =>17]);
        District::create(['id' => '109','name' => "Huyện Lạc Thủy",'city_id' =>17]);
        District::create(['id' => '110','name' => "Thành phố Thái Nguyên",'city_id' =>19]);
        District::create(['id' => '111','name' => "Thành phố Sông Công",'city_id' =>19]);
        District::create(['id' => '112','name' => "Huyện Định Hóa",'city_id' =>19]);
        District::create(['id' => '113','name' => "Huyện Phú Lương",'city_id' =>19]);
        District::create(['id' => '114','name' => "Huyện Đồng Hỷ",'city_id' =>19]);
        District::create(['id' => '115','name' => "Huyện Võ Nhai",'city_id' =>19]);
        District::create(['id' => '116','name' => "Huyện Đại Từ",'city_id' =>19]);
        District::create(['id' => '117','name' => "Thị xã Phổ Yên",'city_id' =>19]);
        District::create(['id' => '118','name' => "Huyện Phú Bình",'city_id' =>19]);
        District::create(['id' => '119','name' => "Thành phố Lạng Sơn",'city_id' =>20]);
        District::create(['id' => '120','name' => "Huyện Tràng Định",'city_id' =>20]);
        District::create(['id' => '121','name' => "Huyện Bình Gia",'city_id' =>20]);
        District::create(['id' => '122','name' => "Huyện Văn Lãng",'city_id' =>20]);
        District::create(['id' => '123','name' => "Huyện Cao Lộc",'city_id' =>20]);
        District::create(['id' => '124','name' => "Huyện Văn Quan",'city_id' =>20]);
        District::create(['id' => '125','name' => "Huyện Bắc Sơn",'city_id' =>20]);
        District::create(['id' => '126','name' => "Huyện Hữu Lũng",'city_id' =>20]);
        District::create(['id' => '127','name' => "Huyện Chi Lăng",'city_id' =>20]);
        District::create(['id' => '128','name' => "Huyện Lộc Bình",'city_id' =>20]);
        District::create(['id' => '129','name' => "Huyện Đình Lập",'city_id' =>20]);
        District::create(['id' => '130','name' => "Thành phố Hạ Long",'city_id' =>22]);
        District::create(['id' => '131','name' => "Thành phố Móng Cái",'city_id' =>22]);
        District::create(['id' => '132','name' => "Thành phố Cẩm Phả",'city_id' =>22]);
        District::create(['id' => '133','name' => "Thành phố Uông Bí",'city_id' =>22]);
        District::create(['id' => '134','name' => "Huyện Bình Liêu",'city_id' =>22]);
        District::create(['id' => '135','name' => "Huyện Tiên Yên",'city_id' =>22]);
        District::create(['id' => '136','name' => "Huyện Đầm Hà",'city_id' =>22]);
        District::create(['id' => '137','name' => "Huyện Hải Hà",'city_id' =>22]);
        District::create(['id' => '138','name' => "Huyện Ba Chẽ",'city_id' =>22]);
        District::create(['id' => '139','name' => "Huyện Vân Đồn",'city_id' =>22]);
        District::create(['id' => '140','name' => "Thị xã Đông Triều",'city_id' =>22]);
        District::create(['id' => '141','name' => "Thị xã Quảng Yên",'city_id' =>22]);
        District::create(['id' => '142','name' => "Huyện Cô Tô",'city_id' =>22]);
        District::create(['id' => '143','name' => "Thành phố Bắc Giang",'city_id' =>24]);
        District::create(['id' => '144','name' => "Huyện Yên Thế",'city_id' =>24]);
        District::create(['id' => '145','name' => "Huyện Tân Yên",'city_id' =>24]);
        District::create(['id' => '146','name' => "Huyện Lạng Giang",'city_id' =>24]);
        District::create(['id' => '147','name' => "Huyện Lục Nam",'city_id' =>24]);
        District::create(['id' => '148','name' => "Huyện Lục Ngạn",'city_id' =>24]);
        District::create(['id' => '149','name' => "Huyện Sơn Động",'city_id' =>24]);
        District::create(['id' => '150','name' => "Huyện Yên Dũng",'city_id' =>24]);
        District::create(['id' => '151','name' => "Huyện Việt Yên",'city_id' =>24]);
        District::create(['id' => '152','name' => "Huyện Hiệp Hòa",'city_id' =>24]);
        District::create(['id' => '153','name' => "Thành phố Việt Trì",'city_id' =>25]);
        District::create(['id' => '154','name' => "Thị xã Phú Thọ",'city_id' =>25]);
        District::create(['id' => '155','name' => "Huyện Đoan Hùng",'city_id' =>25]);
        District::create(['id' => '156','name' => "Huyện Hạ Hoà",'city_id' =>25]);
        District::create(['id' => '157','name' => "Huyện Thanh Ba",'city_id' =>25]);
        District::create(['id' => '158','name' => "Huyện Phù Ninh",'city_id' =>25]);
        District::create(['id' => '159','name' => "Huyện Yên Lập",'city_id' =>25]);
        District::create(['id' => '160','name' => "Huyện Cẩm Khê",'city_id' =>25]);
        District::create(['id' => '161','name' => "Huyện Tam Nông",'city_id' =>25]);
        District::create(['id' => '162','name' => "Huyện Lâm Thao",'city_id' =>25]);
        District::create(['id' => '163','name' => "Huyện Thanh Sơn",'city_id' =>25]);
        District::create(['id' => '164','name' => "Huyện Thanh Thuỷ",'city_id' =>25]);
        District::create(['id' => '165','name' => "Huyện Tân Sơn",'city_id' =>25]);
        District::create(['id' => '166','name' => "Thành phố Vĩnh Yên",'city_id' =>26]);
        District::create(['id' => '167','name' => "Thành phố Phúc Yên",'city_id' =>26]);
        District::create(['id' => '168','name' => "Huyện Lập Thạch",'city_id' =>26]);
        District::create(['id' => '169','name' => "Huyện Tam Dương",'city_id' =>26]);
        District::create(['id' => '170','name' => "Huyện Tam Đảo",'city_id' =>26]);
        District::create(['id' => '171','name' => "Huyện Bình Xuyên",'city_id' =>26]);
        District::create(['id' => '172','name' => "Huyện Mê Linh",'city_id' =>1]);
        District::create(['id' => '173','name' => "Huyện Yên Lạc",'city_id' =>26]);
        District::create(['id' => '174','name' => "Huyện Vĩnh Tường",'city_id' =>26]);
        District::create(['id' => '175','name' => "Huyện Sông Lô",'city_id' =>26]);
        District::create(['id' => '176','name' => "Thành phố Bắc Ninh",'city_id' =>27]);
        District::create(['id' => '177','name' => "Huyện Yên Phong",'city_id' =>27]);
        District::create(['id' => '178','name' => "Huyện Quế Võ",'city_id' =>27]);
        District::create(['id' => '179','name' => "Huyện Tiên Du",'city_id' =>27]);
        District::create(['id' => '180','name' => "Thị xã Từ Sơn",'city_id' =>27]);
        District::create(['id' => '181','name' => "Huyện Thuận Thành",'city_id' =>27]);
        District::create(['id' => '182','name' => "Huyện Gia Bình",'city_id' =>27]);
        District::create(['id' => '183','name' => "Huyện Lương Tài",'city_id' =>27]);
        District::create(['id' => '184','name' => "Quận Hà Đông",'city_id' =>1]);
        District::create(['id' => '185','name' => "Thị xã Sơn Tây",'city_id' =>1]);
        District::create(['id' => '186','name' => "Huyện Ba Vì",'city_id' =>1]);
        District::create(['id' => '187','name' => "Huyện Phúc Thọ",'city_id' =>1]);
        District::create(['id' => '188','name' => "Huyện Đan Phượng",'city_id' =>1]);
        District::create(['id' => '189','name' => "Huyện Hoài Đức",'city_id' =>1]);
        District::create(['id' => '190','name' => "Huyện Quốc Oai",'city_id' =>1]);
        District::create(['id' => '191','name' => "Huyện Thạch Thất",'city_id' =>1]);
        District::create(['id' => '192','name' => "Huyện Chương Mỹ",'city_id' =>1]);
        District::create(['id' => '193','name' => "Huyện Thanh Oai",'city_id' =>1]);
        District::create(['id' => '194','name' => "Huyện Thường Tín",'city_id' =>1]);
        District::create(['id' => '195','name' => "Huyện Phú Xuyên",'city_id' =>1]);
        District::create(['id' => '196','name' => "Huyện Ứng Hòa",'city_id' =>1]);
        District::create(['id' => '197','name' => "Huyện Mỹ Đức",'city_id' =>1]);
        District::create(['id' => '198','name' => "Thành phố Hải Dương",'city_id' =>30]);
        District::create(['id' => '199','name' => "Thành phố Chí Linh",'city_id' =>30]);
        District::create(['id' => '200','name' => "Huyện Nam Sách",'city_id' =>30]);
        District::create(['id' => '201','name' => "Thị xã Kinh Môn",'city_id' =>30]);
        District::create(['id' => '202','name' => "Huyện Kim Thành",'city_id' =>30]);
        District::create(['id' => '203','name' => "Huyện Thanh Hà",'city_id' =>30]);
        District::create(['id' => '204','name' => "Huyện Cẩm Giàng",'city_id' =>30]);
        District::create(['id' => '205','name' => "Huyện Bình Giang",'city_id' =>30]);
        District::create(['id' => '206','name' => "Huyện Gia Lộc",'city_id' =>30]);
        District::create(['id' => '207','name' => "Huyện Tứ Kỳ",'city_id' =>30]);
        District::create(['id' => '208','name' => "Huyện Ninh Giang",'city_id' =>30]);
        District::create(['id' => '209','name' => "Huyện Thanh Miện",'city_id' =>30]);
        District::create(['id' => '210','name' => "Quận Hồng Bàng",'city_id' =>31]);
        District::create(['id' => '211','name' => "Quận Ngô Quyền",'city_id' =>31]);
        District::create(['id' => '212','name' => "Quận Lê Chân",'city_id' =>31]);
        District::create(['id' => '213','name' => "Quận Hải An",'city_id' =>31]);
        District::create(['id' => '214','name' => "Quận Kiến An",'city_id' =>31]);
        District::create(['id' => '215','name' => "Quận Đồ Sơn",'city_id' =>31]);
        District::create(['id' => '216','name' => "Quận Dương Kinh",'city_id' =>31]);
        District::create(['id' => '217','name' => "Huyện Thuỷ Nguyên",'city_id' =>31]);
        District::create(['id' => '218','name' => "Huyện An Dương",'city_id' =>31]);
        District::create(['id' => '219','name' => "Huyện An Lão",'city_id' =>31]);
        District::create(['id' => '220','name' => "Huyện Kiến Thuỵ",'city_id' =>31]);
        District::create(['id' => '221','name' => "Huyện Tiên Lãng",'city_id' =>31]);
        District::create(['id' => '222','name' => "Huyện Vĩnh Bảo",'city_id' =>31]);
        District::create(['id' => '223','name' => "Huyện Cát Hải",'city_id' =>31]);
        District::create(['id' => '224','name' => "Huyện Bạch Long Vĩ",'city_id' =>31]);
        District::create(['id' => '225','name' => "Thành phố Hưng Yên",'city_id' =>33]);
        District::create(['id' => '226','name' => "Huyện Văn Lâm",'city_id' =>33]);
        District::create(['id' => '227','name' => "Huyện Văn Giang",'city_id' =>33]);
        District::create(['id' => '228','name' => "Huyện Yên Mỹ",'city_id' =>33]);
        District::create(['id' => '229','name' => "Thị xã Mỹ Hào",'city_id' =>33]);
        District::create(['id' => '230','name' => "Huyện Ân Thi",'city_id' =>33]);
        District::create(['id' => '231','name' => "Huyện Khoái Châu",'city_id' =>33]);
        District::create(['id' => '232','name' => "Huyện Kim Động",'city_id' =>33]);
        District::create(['id' => '233','name' => "Huyện Tiên Lữ",'city_id' =>33]);
        District::create(['id' => '234','name' => "Huyện Phù Cừ",'city_id' =>33]);
        District::create(['id' => '235','name' => "Thành phố Thái Bình",'city_id' =>34]);
        District::create(['id' => '236','name' => "Huyện Quỳnh Phụ",'city_id' =>34]);
        District::create(['id' => '237','name' => "Huyện Hưng Hà",'city_id' =>34]);
        District::create(['id' => '238','name' => "Huyện Đông Hưng",'city_id' =>34]);
        District::create(['id' => '239','name' => "Huyện Thái Thụy",'city_id' =>34]);
        District::create(['id' => '240','name' => "Huyện Tiền Hải",'city_id' =>34]);
        District::create(['id' => '241','name' => "Huyện Kiến Xương",'city_id' =>34]);
        District::create(['id' => '242','name' => "Huyện Vũ Thư",'city_id' =>34]);
        District::create(['id' => '243','name' => "Thành phố Phủ Lý",'city_id' =>35]);
        District::create(['id' => '244','name' => "Thị xã Duy Tiên",'city_id' =>35]);
        District::create(['id' => '245','name' => "Huyện Kim Bảng",'city_id' =>35]);
        District::create(['id' => '246','name' => "Huyện Thanh Liêm",'city_id' =>35]);
        District::create(['id' => '247','name' => "Huyện Bình Lục",'city_id' =>35]);
        District::create(['id' => '248','name' => "Huyện Lý Nhân",'city_id' =>35]);
        District::create(['id' => '249','name' => "Thành phố Nam Định",'city_id' =>36]);
        District::create(['id' => '250','name' => "Huyện Mỹ Lộc",'city_id' =>36]);
        District::create(['id' => '251','name' => "Huyện Vụ Bản",'city_id' =>36]);
        District::create(['id' => '252','name' => "Huyện Ý Yên",'city_id' =>36]);
        District::create(['id' => '253','name' => "Huyện Nghĩa Hưng",'city_id' =>36]);
        District::create(['id' => '254','name' => "Huyện Nam Trực",'city_id' =>36]);
        District::create(['id' => '255','name' => "Huyện Trực Ninh",'city_id' =>36]);
        District::create(['id' => '256','name' => "Huyện Xuân Trường",'city_id' =>36]);
        District::create(['id' => '257','name' => "Huyện Giao Thủy",'city_id' =>36]);
        District::create(['id' => '258','name' => "Huyện Hải Hậu",'city_id' =>36]);
        District::create(['id' => '259','name' => "Thành phố Ninh Bình",'city_id' =>37]);
        District::create(['id' => '260','name' => "Thành phố Tam Điệp",'city_id' =>37]);
        District::create(['id' => '261','name' => "Huyện Nho Quan",'city_id' =>37]);
        District::create(['id' => '262','name' => "Huyện Gia Viễn",'city_id' =>37]);
        District::create(['id' => '263','name' => "Huyện Hoa Lư",'city_id' =>37]);
        District::create(['id' => '264','name' => "Huyện Yên Khánh",'city_id' =>37]);
        District::create(['id' => '265','name' => "Huyện Kim Sơn",'city_id' =>37]);
        District::create(['id' => '266','name' => "Huyện Yên Mô",'city_id' =>37]);
        District::create(['id' => '267','name' => "Thành phố Thanh Hóa",'city_id' =>38]);
        District::create(['id' => '268','name' => "Thị xã Bỉm Sơn",'city_id' =>38]);
        District::create(['id' => '269','name' => "Thành phố Sầm Sơn",'city_id' =>38]);
        District::create(['id' => '270','name' => "Huyện Mường Lát",'city_id' =>38]);
        District::create(['id' => '271','name' => "Huyện Quan Hóa",'city_id' =>38]);
        District::create(['id' => '272','name' => "Huyện Bá Thước",'city_id' =>38]);
        District::create(['id' => '273','name' => "Huyện Quan Sơn",'city_id' =>38]);
        District::create(['id' => '274','name' => "Huyện Lang Chánh",'city_id' =>38]);
        District::create(['id' => '275','name' => "Huyện Ngọc Lặc",'city_id' =>38]);
        District::create(['id' => '276','name' => "Huyện Cẩm Thủy",'city_id' =>38]);
        District::create(['id' => '277','name' => "Huyện Thạch Thành",'city_id' =>38]);
        District::create(['id' => '278','name' => "Huyện Hà Trung",'city_id' =>38]);
        District::create(['id' => '279','name' => "Huyện Vĩnh Lộc",'city_id' =>38]);
        District::create(['id' => '280','name' => "Huyện Yên Định",'city_id' =>38]);
        District::create(['id' => '281','name' => "Huyện Thọ Xuân",'city_id' =>38]);
        District::create(['id' => '282','name' => "Huyện Thường Xuân",'city_id' =>38]);
        District::create(['id' => '283','name' => "Huyện Triệu Sơn",'city_id' =>38]);
        District::create(['id' => '284','name' => "Huyện Thiệu Hóa",'city_id' =>38]);
        District::create(['id' => '285','name' => "Huyện Hoằng Hóa",'city_id' =>38]);
        District::create(['id' => '286','name' => "Huyện Hậu Lộc",'city_id' =>38]);
        District::create(['id' => '287','name' => "Huyện Nga Sơn",'city_id' =>38]);
        District::create(['id' => '288','name' => "Huyện Như Xuân",'city_id' =>38]);
        District::create(['id' => '289','name' => "Huyện Như Thanh",'city_id' =>38]);
        District::create(['id' => '290','name' => "Huyện Nông Cống",'city_id' =>38]);
        District::create(['id' => '291','name' => "Huyện Đông Sơn",'city_id' =>38]);
        District::create(['id' => '292','name' => "Huyện Quảng Xương",'city_id' =>38]);
        District::create(['id' => '293','name' => "Thị xã Nghi Sơn",'city_id' =>38]);
        District::create(['id' => '294','name' => "Thành phố Vinh",'city_id' =>40]);
        District::create(['id' => '295','name' => "Thị xã Cửa Lò",'city_id' =>40]);
        District::create(['id' => '296','name' => "Thị xã Thái Hoà",'city_id' =>40]);
        District::create(['id' => '297','name' => "Huyện Quế Phong",'city_id' =>40]);
        District::create(['id' => '298','name' => "Huyện Quỳ Châu",'city_id' =>40]);
        District::create(['id' => '299','name' => "Huyện Kỳ Sơn",'city_id' =>40]);
        District::create(['id' => '300','name' => "Huyện Tương Dương",'city_id' =>40]);
        District::create(['id' => '301','name' => "Huyện Nghĩa Đàn",'city_id' =>40]);
        District::create(['id' => '302','name' => "Huyện Quỳ Hợp",'city_id' =>40]);
        District::create(['id' => '303','name' => "Huyện Quỳnh Lưu",'city_id' =>40]);
        District::create(['id' => '304','name' => "Huyện Con Cuông",'city_id' =>40]);
        District::create(['id' => '305','name' => "Huyện Tân Kỳ",'city_id' =>40]);
        District::create(['id' => '306','name' => "Huyện Anh Sơn",'city_id' =>40]);
        District::create(['id' => '307','name' => "Huyện Diễn Châu",'city_id' =>40]);
        District::create(['id' => '308','name' => "Huyện Yên Thành",'city_id' =>40]);
        District::create(['id' => '309','name' => "Huyện Đô Lương",'city_id' =>40]);
        District::create(['id' => '310','name' => "Huyện Thanh Chương",'city_id' =>40]);
        District::create(['id' => '311','name' => "Huyện Nghi Lộc",'city_id' =>40]);
        District::create(['id' => '312','name' => "Huyện Nam Đàn",'city_id' =>40]);
        District::create(['id' => '313','name' => "Huyện Hưng Nguyên",'city_id' =>40]);
        District::create(['id' => '314','name' => "Thị xã Hoàng Mai",'city_id' =>40]);
        District::create(['id' => '315','name' => "Thành phố Hà Tĩnh",'city_id' =>42]);
        District::create(['id' => '316','name' => "Thị xã Hồng Lĩnh",'city_id' =>42]);
        District::create(['id' => '317','name' => "Huyện Hương Sơn",'city_id' =>42]);
        District::create(['id' => '318','name' => "Huyện Đức Thọ",'city_id' =>42]);
        District::create(['id' => '319','name' => "Huyện Vũ Quang",'city_id' =>42]);
        District::create(['id' => '320','name' => "Huyện Nghi Xuân",'city_id' =>42]);
        District::create(['id' => '321','name' => "Huyện Can Lộc",'city_id' =>42]);
        District::create(['id' => '322','name' => "Huyện Hương Khê",'city_id' =>42]);
        District::create(['id' => '323','name' => "Huyện Thạch Hà",'city_id' =>42]);
        District::create(['id' => '324','name' => "Huyện Cẩm Xuyên",'city_id' =>42]);
        District::create(['id' => '325','name' => "Huyện Kỳ Anh",'city_id' =>42]);
        District::create(['id' => '326','name' => "Huyện Lộc Hà",'city_id' =>42]);
        District::create(['id' => '327','name' => "Thị xã Kỳ Anh",'city_id' =>42]);
        District::create(['id' => '328','name' => "Thành Phố Đồng Hới",'city_id' =>44]);
        District::create(['id' => '329','name' => "Huyện Minh Hóa",'city_id' =>44]);
        District::create(['id' => '330','name' => "Huyện Tuyên Hóa",'city_id' =>44]);
        District::create(['id' => '331','name' => "Huyện Quảng Trạch",'city_id' =>44]);
        District::create(['id' => '332','name' => "Huyện Bố Trạch",'city_id' =>44]);
        District::create(['id' => '333','name' => "Huyện Quảng Ninh",'city_id' =>44]);
        District::create(['id' => '334','name' => "Huyện Lệ Thủy",'city_id' =>44]);
        District::create(['id' => '335','name' => "Thị xã Ba Đồn",'city_id' =>44]);
        District::create(['id' => '336','name' => "Thành phố Đông Hà",'city_id' =>45]);
        District::create(['id' => '337','name' => "Thị xã Quảng Trị",'city_id' =>45]);
        District::create(['id' => '338','name' => "Huyện Vĩnh Linh",'city_id' =>45]);
        District::create(['id' => '339','name' => "Huyện Hướng Hóa",'city_id' =>45]);
        District::create(['id' => '340','name' => "Huyện Gio Linh",'city_id' =>45]);
        District::create(['id' => '341','name' => "Huyện Đa Krông",'city_id' =>45]);
        District::create(['id' => '342','name' => "Huyện Cam Lộ",'city_id' =>45]);
        District::create(['id' => '343','name' => "Huyện Triệu Phong",'city_id' =>45]);
        District::create(['id' => '344','name' => "Huyện Hải Lăng",'city_id' =>45]);
        District::create(['id' => '345','name' => "Huyện Cồn Cỏ",'city_id' =>45]);
        District::create(['id' => '346','name' => "Thành phố Huế",'city_id' =>46]);
        District::create(['id' => '347','name' => "Huyện Phong Điền",'city_id' =>46]);
        District::create(['id' => '348','name' => "Huyện Quảng Điền",'city_id' =>46]);
        District::create(['id' => '349','name' => "Huyện Phú Vang",'city_id' =>46]);
        District::create(['id' => '350','name' => "Thị xã Hương Thủy",'city_id' =>46]);
        District::create(['id' => '351','name' => "Thị xã Hương Trà",'city_id' =>46]);
        District::create(['id' => '352','name' => "Huyện A Lưới",'city_id' =>46]);
        District::create(['id' => '353','name' => "Huyện Phú Lộc",'city_id' =>46]);
        District::create(['id' => '354','name' => "Huyện Nam Đông",'city_id' =>46]);
        District::create(['id' => '355','name' => "Quận Liên Chiểu",'city_id' =>48]);
        District::create(['id' => '356','name' => "Quận Thanh Khê",'city_id' =>48]);
        District::create(['id' => '357','name' => "Quận Hải Châu",'city_id' =>48]);
        District::create(['id' => '358','name' => "Quận Sơn Trà",'city_id' =>48]);
        District::create(['id' => '359','name' => "Quận Ngũ Hành Sơn",'city_id' =>48]);
        District::create(['id' => '360','name' => "Quận Cẩm Lệ",'city_id' =>48]);
        District::create(['id' => '361','name' => "Huyện Hòa Vang",'city_id' =>48]);
        District::create(['id' => '362','name' => "Huyện Hoàng Sa",'city_id' =>48]);
        District::create(['id' => '363','name' => "Thành phố Tam Kỳ",'city_id' =>49]);
        District::create(['id' => '364','name' => "Thành phố Hội An",'city_id' =>49]);
        District::create(['id' => '365','name' => "Huyện Tây Giang",'city_id' =>49]);
        District::create(['id' => '366','name' => "Huyện Đông Giang",'city_id' =>49]);
        District::create(['id' => '367','name' => "Huyện Đại Lộc",'city_id' =>49]);
        District::create(['id' => '368','name' => "Thị xã Điện Bàn",'city_id' =>49]);
        District::create(['id' => '369','name' => "Huyện Duy Xuyên",'city_id' =>49]);
        District::create(['id' => '370','name' => "Huyện Quế Sơn",'city_id' =>49]);
        District::create(['id' => '371','name' => "Huyện Nam Giang",'city_id' =>49]);
        District::create(['id' => '372','name' => "Huyện Phước Sơn",'city_id' =>49]);
        District::create(['id' => '373','name' => "Huyện Hiệp Đức",'city_id' =>49]);
        District::create(['id' => '374','name' => "Huyện Thăng Bình",'city_id' =>49]);
        District::create(['id' => '375','name' => "Huyện Tiên Phước",'city_id' =>49]);
        District::create(['id' => '376','name' => "Huyện Bắc Trà My",'city_id' =>49]);
        District::create(['id' => '377','name' => "Huyện Nam Trà My",'city_id' =>49]);
        District::create(['id' => '378','name' => "Huyện Núi Thành",'city_id' =>49]);
        District::create(['id' => '379','name' => "Huyện Phú Ninh",'city_id' =>49]);
        District::create(['id' => '380','name' => "Huyện Nông Sơn",'city_id' =>49]);
        District::create(['id' => '381','name' => "Thành phố Quảng Ngãi",'city_id' =>51]);
        District::create(['id' => '382','name' => "Huyện Bình Sơn",'city_id' =>51]);
        District::create(['id' => '383','name' => "Huyện Trà Bồng",'city_id' =>51]);
        District::create(['id' => '384','name' => "Huyện Sơn Tịnh",'city_id' =>51]);
        District::create(['id' => '385','name' => "Huyện Tư Nghĩa",'city_id' =>51]);
        District::create(['id' => '386','name' => "Huyện Sơn Hà",'city_id' =>51]);
        District::create(['id' => '387','name' => "Huyện Sơn Tây",'city_id' =>51]);
        District::create(['id' => '388','name' => "Huyện Minh Long",'city_id' =>51]);
        District::create(['id' => '389','name' => "Huyện Nghĩa Hành",'city_id' =>51]);
        District::create(['id' => '390','name' => "Huyện Mộ Đức",'city_id' =>51]);
        District::create(['id' => '391','name' => "Thị xã Đức Phổ",'city_id' =>51]);
        District::create(['id' => '392','name' => "Huyện Ba Tơ",'city_id' =>51]);
        District::create(['id' => '393','name' => "Huyện Lý Sơn",'city_id' =>51]);
        District::create(['id' => '394','name' => "Thành phố Quy Nhơn",'city_id' =>52]);
        District::create(['id' => '395','name' => "Huyện An Lão",'city_id' =>52]);
        District::create(['id' => '396','name' => "Thị xã Hoài Nhơn",'city_id' =>52]);
        District::create(['id' => '397','name' => "Huyện Hoài Ân",'city_id' =>52]);
        District::create(['id' => '398','name' => "Huyện Phù Mỹ",'city_id' =>52]);
        District::create(['id' => '399','name' => "Huyện Vĩnh Thạnh",'city_id' =>52]);
        District::create(['id' => '400','name' => "Huyện Tây Sơn",'city_id' =>52]);
        District::create(['id' => '401','name' => "Huyện Phù Cát",'city_id' =>52]);
        District::create(['id' => '402','name' => "Thị xã An Nhơn",'city_id' =>52]);
        District::create(['id' => '403','name' => "Huyện Tuy Phước",'city_id' =>52]);
        District::create(['id' => '404','name' => "Huyện Vân Canh",'city_id' =>52]);
        District::create(['id' => '405','name' => "Thành phố Tuy Hoà",'city_id' =>54]);
        District::create(['id' => '406','name' => "Thị xã Sông Cầu",'city_id' =>54]);
        District::create(['id' => '407','name' => "Huyện Đồng Xuân",'city_id' =>54]);
        District::create(['id' => '408','name' => "Huyện Tuy An",'city_id' =>54]);
        District::create(['id' => '409','name' => "Huyện Sơn Hòa",'city_id' =>54]);
        District::create(['id' => '410','name' => "Huyện Sông Hinh",'city_id' =>54]);
        District::create(['id' => '411','name' => "Huyện Tây Hoà",'city_id' =>54]);
        District::create(['id' => '412','name' => "Huyện Phú Hoà",'city_id' =>54]);
        District::create(['id' => '413','name' => "Thị xã Đông Hòa",'city_id' =>54]);
        District::create(['id' => '414','name' => "Thành phố Nha Trang",'city_id' =>56]);
        District::create(['id' => '415','name' => "Thành phố Cam Ranh",'city_id' =>56]);
        District::create(['id' => '416','name' => "Huyện Cam Lâm",'city_id' =>56]);
        District::create(['id' => '417','name' => "Huyện Vạn Ninh",'city_id' =>56]);
        District::create(['id' => '418','name' => "Thị xã Ninh Hòa",'city_id' =>56]);
        District::create(['id' => '419','name' => "Huyện Khánh Vĩnh",'city_id' =>56]);
        District::create(['id' => '420','name' => "Huyện Diên Khánh",'city_id' =>56]);
        District::create(['id' => '421','name' => "Huyện Khánh Sơn",'city_id' =>56]);
        District::create(['id' => '422','name' => "Huyện Trường Sa",'city_id' =>56]);
        District::create(['id' => '423','name' => "Thành phố Phan Rang-Tháp Chàm",'city_id' =>58]);
        District::create(['id' => '424','name' => "Huyện Bác Ái",'city_id' =>58]);
        District::create(['id' => '425','name' => "Huyện Ninh Sơn",'city_id' =>58]);
        District::create(['id' => '426','name' => "Huyện Ninh Hải",'city_id' =>58]);
        District::create(['id' => '427','name' => "Huyện Ninh Phước",'city_id' =>58]);
        District::create(['id' => '428','name' => "Huyện Thuận Bắc",'city_id' =>58]);
        District::create(['id' => '429','name' => "Huyện Thuận Nam",'city_id' =>58]);
        District::create(['id' => '430','name' => "Thành phố Phan Thiết",'city_id' =>60]);
        District::create(['id' => '431','name' => "Thị xã La Gi",'city_id' =>60]);
        District::create(['id' => '432','name' => "Huyện Tuy Phong",'city_id' =>60]);
        District::create(['id' => '433','name' => "Huyện Bắc Bình",'city_id' =>60]);
        District::create(['id' => '434','name' => "Huyện Hàm Thuận Bắc",'city_id' =>60]);
        District::create(['id' => '435','name' => "Huyện Hàm Thuận Nam",'city_id' =>60]);
        District::create(['id' => '436','name' => "Huyện Tánh Linh",'city_id' =>60]);
        District::create(['id' => '437','name' => "Huyện Đức Linh",'city_id' =>60]);
        District::create(['id' => '438','name' => "Huyện Hàm Tân",'city_id' =>60]);
        District::create(['id' => '439','name' => "Huyện Phú Quí",'city_id' =>60]);
        District::create(['id' => '440','name' => "Thành phố Kon Tum",'city_id' =>62]);
        District::create(['id' => '441','name' => "Huyện Đắk Glei",'city_id' =>62]);
        District::create(['id' => '442','name' => "Huyện Ngọc Hồi",'city_id' =>62]);
        District::create(['id' => '443','name' => "Huyện Đắk Tô",'city_id' =>62]);
        District::create(['id' => '444','name' => "Huyện Kon Plông",'city_id' =>62]);
        District::create(['id' => '445','name' => "Huyện Kon Rẫy",'city_id' =>62]);
        District::create(['id' => '446','name' => "Huyện Đắk Hà",'city_id' =>62]);
        District::create(['id' => '447','name' => "Huyện Sa Thầy",'city_id' =>62]);
        District::create(['id' => '448','name' => "Huyện Tu Mơ Rông",'city_id' =>62]);
        District::create(['id' => '449','name' => "Huyện Ia H' Drai",'city_id' =>62]);
        District::create(['id' => '450','name' => "Thành phố Pleiku",'city_id' =>64]);
        District::create(['id' => '451','name' => "Thị xã An Khê",'city_id' =>64]);
        District::create(['id' => '452','name' => "Thị xã Ayun Pa",'city_id' =>64]);
        District::create(['id' => '453','name' => "Huyện KBang",'city_id' =>64]);
        District::create(['id' => '454','name' => "Huyện Đăk Đoa",'city_id' =>64]);
        District::create(['id' => '455','name' => "Huyện Chư Păh",'city_id' =>64]);
        District::create(['id' => '456','name' => "Huyện Ia Grai",'city_id' =>64]);
        District::create(['id' => '457','name' => "Huyện Mang Yang",'city_id' =>64]);
        District::create(['id' => '458','name' => "Huyện Kông Chro",'city_id' =>64]);
        District::create(['id' => '459','name' => "Huyện Đức Cơ",'city_id' =>64]);
        District::create(['id' => '460','name' => "Huyện Chư Prông",'city_id' =>64]);
        District::create(['id' => '461','name' => "Huyện Chư Sê",'city_id' =>64]);
        District::create(['id' => '462','name' => "Huyện Đăk Pơ",'city_id' =>64]);
        District::create(['id' => '463','name' => "Huyện Ia Pa",'city_id' =>64]);
        District::create(['id' => '464','name' => "Huyện Krông Pa",'city_id' =>64]);
        District::create(['id' => '465','name' => "Huyện Phú Thiện",'city_id' =>64]);
        District::create(['id' => '466','name' => "Huyện Chư Pưh",'city_id' =>64]);
        District::create(['id' => '467','name' => "Thành phố Buôn Ma Thuột",'city_id' =>66]);
        District::create(['id' => '468','name' => "Thị Xã Buôn Hồ",'city_id' =>66]);
        District::create(['id' => '469','name' => "Huyện Ea H'leo",'city_id' =>66]);
        District::create(['id' => '470','name' => "Huyện Ea Súp",'city_id' =>66]);
        District::create(['id' => '471','name' => "Huyện Buôn Đôn",'city_id' =>66]);
        District::create(['id' => '472','name' => "Huyện Cư M'gar",'city_id' =>66]);
        District::create(['id' => '473','name' => "Huyện Krông Búk",'city_id' =>66]);
        District::create(['id' => '474','name' => "Huyện Krông Năng",'city_id' =>66]);
        District::create(['id' => '475','name' => "Huyện Ea Kar",'city_id' =>66]);
        District::create(['id' => '476','name' => "Huyện M'Đrắk",'city_id' =>66]);
        District::create(['id' => '477','name' => "Huyện Krông Bông",'city_id' =>66]);
        District::create(['id' => '478','name' => "Huyện Krông Pắc",'city_id' =>66]);
        District::create(['id' => '479','name' => "Huyện Krông A Na",'city_id' =>66]);
        District::create(['id' => '480','name' => "Huyện Lắk",'city_id' =>66]);
        District::create(['id' => '481','name' => "Huyện Cư Kuin",'city_id' =>66]);
        District::create(['id' => '482','name' => "Thành phố Gia Nghĩa",'city_id' =>67]);
        District::create(['id' => '483','name' => "Huyện Đăk Glong",'city_id' =>67]);
        District::create(['id' => '484','name' => "Huyện Cư Jút",'city_id' =>67]);
        District::create(['id' => '485','name' => "Huyện Đắk Mil",'city_id' =>67]);
        District::create(['id' => '486','name' => "Huyện Krông Nô",'city_id' =>67]);
        District::create(['id' => '487','name' => "Huyện Đắk Song",'city_id' =>67]);
        District::create(['id' => '488','name' => "Huyện Đắk R'Lấp",'city_id' =>67]);
        District::create(['id' => '489','name' => "Huyện Tuy Đức",'city_id' =>67]);
        District::create(['id' => '490','name' => "Thành phố Đà Lạt",'city_id' =>68]);
        District::create(['id' => '491','name' => "Thành phố Bảo Lộc",'city_id' =>68]);
        District::create(['id' => '492','name' => "Huyện Đam Rông",'city_id' =>68]);
        District::create(['id' => '493','name' => "Huyện Lạc Dương",'city_id' =>68]);
        District::create(['id' => '494','name' => "Huyện Lâm Hà",'city_id' =>68]);
        District::create(['id' => '495','name' => "Huyện Đơn Dương",'city_id' =>68]);
        District::create(['id' => '496','name' => "Huyện Đức Trọng",'city_id' =>68]);
        District::create(['id' => '497','name' => "Huyện Di Linh",'city_id' =>68]);
        District::create(['id' => '498','name' => "Huyện Bảo Lâm",'city_id' =>68]);
        District::create(['id' => '499','name' => "Huyện Đạ Huoai",'city_id' =>68]);
        District::create(['id' => '500','name' => "Huyện Đạ Tẻh",'city_id' =>68]);
        District::create(['id' => '501','name' => "Huyện Cát Tiên",'city_id' =>68]);
        District::create(['id' => '502','name' => "Thị xã Phước Long",'city_id' =>70]);
        District::create(['id' => '503','name' => "Thành phố Đồng Xoài",'city_id' =>70]);
        District::create(['id' => '504','name' => "Thị xã Bình Long",'city_id' =>70]);
        District::create(['id' => '505','name' => "Huyện Bù Gia Mập",'city_id' =>70]);
        District::create(['id' => '506','name' => "Huyện Lộc Ninh",'city_id' =>70]);
        District::create(['id' => '507','name' => "Huyện Bù Đốp",'city_id' =>70]);
        District::create(['id' => '508','name' => "Huyện Hớn Quản",'city_id' =>70]);
        District::create(['id' => '509','name' => "Huyện Đồng Phú",'city_id' =>70]);
        District::create(['id' => '510','name' => "Huyện Bù Đăng",'city_id' =>70]);
        District::create(['id' => '511','name' => "Huyện Chơn Thành",'city_id' =>70]);
        District::create(['id' => '512','name' => "Huyện Phú Riềng",'city_id' =>70]);
        District::create(['id' => '513','name' => "Thành phố Tây Ninh",'city_id' =>72]);
        District::create(['id' => '514','name' => "Huyện Tân Biên",'city_id' =>72]);
        District::create(['id' => '515','name' => "Huyện Tân Châu",'city_id' =>72]);
        District::create(['id' => '516','name' => "Huyện Dương Minh Châu",'city_id' =>72]);
        District::create(['id' => '517','name' => "Huyện Châu Thành",'city_id' =>72]);
        District::create(['id' => '518','name' => "Thị xã Hòa Thành",'city_id' =>72]);
        District::create(['id' => '519','name' => "Huyện Gò Dầu",'city_id' =>72]);
        District::create(['id' => '520','name' => "Huyện Bến Cầu",'city_id' =>72]);
        District::create(['id' => '521','name' => "Thị xã Trảng Bàng",'city_id' =>72]);
        District::create(['id' => '522','name' => "Thành phố Thủ Dầu Một",'city_id' =>74]);
        District::create(['id' => '523','name' => "Huyện Bàu Bàng",'city_id' =>74]);
        District::create(['id' => '524','name' => "Huyện Dầu Tiếng",'city_id' =>74]);
        District::create(['id' => '525','name' => "Thị xã Bến Cát",'city_id' =>74]);
        District::create(['id' => '526','name' => "Huyện Phú Giáo",'city_id' =>74]);
        District::create(['id' => '527','name' => "Thị xã Tân Uyên",'city_id' =>74]);
        District::create(['id' => '528','name' => "Thành phố Dĩ An",'city_id' =>74]);
        District::create(['id' => '529','name' => "Thành phố Thuận An",'city_id' =>74]);
        District::create(['id' => '530','name' => "Huyện Bắc Tân Uyên",'city_id' =>74]);
        District::create(['id' => '531','name' => "Thành phố Biên Hòa",'city_id' =>75]);
        District::create(['id' => '532','name' => "Thành phố Long Khánh",'city_id' =>75]);
        District::create(['id' => '533','name' => "Huyện Tân Phú",'city_id' =>75]);
        District::create(['id' => '534','name' => "Huyện Vĩnh Cửu",'city_id' =>75]);
        District::create(['id' => '535','name' => "Huyện Định Quán",'city_id' =>75]);
        District::create(['id' => '536','name' => "Huyện Trảng Bom",'city_id' =>75]);
        District::create(['id' => '537','name' => "Huyện Thống Nhất",'city_id' =>75]);
        District::create(['id' => '538','name' => "Huyện Cẩm Mỹ",'city_id' =>75]);
        District::create(['id' => '539','name' => "Huyện Long Thành",'city_id' =>75]);
        District::create(['id' => '540','name' => "Huyện Xuân Lộc",'city_id' =>75]);
        District::create(['id' => '541','name' => "Huyện Nhơn Trạch",'city_id' =>75]);
        District::create(['id' => '542','name' => "Thành phố Vũng Tàu",'city_id' =>77]);
        District::create(['id' => '543','name' => "Thành phố Bà Rịa",'city_id' =>77]);
        District::create(['id' => '544','name' => "Huyện Châu Đức",'city_id' =>77]);
        District::create(['id' => '545','name' => "Huyện Xuyên Mộc",'city_id' =>77]);
        District::create(['id' => '546','name' => "Huyện Long Điền",'city_id' =>77]);
        District::create(['id' => '547','name' => "Huyện Đất Đỏ",'city_id' =>77]);
        District::create(['id' => '548','name' => "Thị xã Phú Mỹ",'city_id' =>77]);
        District::create(['id' => '549','name' => "Huyện Côn Đảo",'city_id' =>77]);
        District::create(['id' => '550','name' => "Quận 1",'city_id' =>79]);
        District::create(['id' => '551','name' => "Quận 12",'city_id' =>79]);
        District::create(['id' => '552','name' => "Quận Gò Vấp",'city_id' =>79]);
        District::create(['id' => '553','name' => "Quận Bình Thạnh",'city_id' =>79]);
        District::create(['id' => '554','name' => "Quận Tân Bình",'city_id' =>79]);
        District::create(['id' => '555','name' => "Quận Tân Phú",'city_id' =>79]);
        District::create(['id' => '556','name' => "Quận Phú Nhuận",'city_id' =>79]);
        District::create(['id' => '557','name' => "Thành phố Thủ Đức",'city_id' =>79]);
        District::create(['id' => '558','name' => "Quận 3",'city_id' =>79]);
        District::create(['id' => '559','name' => "Quận 10",'city_id' =>79]);
        District::create(['id' => '560','name' => "Quận 11",'city_id' =>79]);
        District::create(['id' => '561','name' => "Quận 4",'city_id' =>79]);
        District::create(['id' => '562','name' => "Quận 5",'city_id' =>79]);
        District::create(['id' => '563','name' => "Quận 6",'city_id' =>79]);
        District::create(['id' => '564','name' => "Quận 8",'city_id' =>79]);
        District::create(['id' => '565','name' => "Quận Bình Tân",'city_id' =>79]);
        District::create(['id' => '566','name' => "Quận 7",'city_id' =>79]);
        District::create(['id' => '567','name' => "Huyện Củ Chi",'city_id' =>79]);
        District::create(['id' => '568','name' => "Huyện Hóc Môn",'city_id' =>79]);
        District::create(['id' => '569','name' => "Huyện Bình Chánh",'city_id' =>79]);
        District::create(['id' => '570','name' => "Huyện Nhà Bè",'city_id' =>79]);
        District::create(['id' => '571','name' => "Huyện Cần Giờ",'city_id' =>79]);
        District::create(['id' => '572','name' => "Thành phố Tân An",'city_id' =>80]);
        District::create(['id' => '573','name' => "Thị xã Kiến Tường",'city_id' =>80]);
        District::create(['id' => '574','name' => "Huyện Tân Hưng",'city_id' =>80]);
        District::create(['id' => '575','name' => "Huyện Vĩnh Hưng",'city_id' =>80]);
        District::create(['id' => '576','name' => "Huyện Mộc Hóa",'city_id' =>80]);
        District::create(['id' => '577','name' => "Huyện Tân Thạnh",'city_id' =>80]);
        District::create(['id' => '578','name' => "Huyện Thạnh Hóa",'city_id' =>80]);
        District::create(['id' => '579','name' => "Huyện Đức Huệ",'city_id' =>80]);
        District::create(['id' => '580','name' => "Huyện Đức Hòa",'city_id' =>80]);
        District::create(['id' => '581','name' => "Huyện Bến Lức",'city_id' =>80]);
        District::create(['id' => '582','name' => "Huyện Thủ Thừa",'city_id' =>80]);
        District::create(['id' => '583','name' => "Huyện Tân Trụ",'city_id' =>80]);
        District::create(['id' => '584','name' => "Huyện Cần Đước",'city_id' =>80]);
        District::create(['id' => '585','name' => "Huyện Cần Giuộc",'city_id' =>80]);
        District::create(['id' => '586','name' => "Huyện Châu Thành",'city_id' =>80]);
        District::create(['id' => '587','name' => "Thành phố Mỹ Tho",'city_id' =>82]);
        District::create(['id' => '588','name' => "Thị xã Gò Công",'city_id' =>82]);
        District::create(['id' => '589','name' => "Thị xã Cai Lậy",'city_id' =>82]);
        District::create(['id' => '590','name' => "Huyện Tân Phước",'city_id' =>82]);
        District::create(['id' => '591','name' => "Huyện Cái Bè",'city_id' =>82]);
        District::create(['id' => '592','name' => "Huyện Cai Lậy",'city_id' =>82]);
        District::create(['id' => '593','name' => "Huyện Châu Thành",'city_id' =>82]);
        District::create(['id' => '594','name' => "Huyện Chợ Gạo",'city_id' =>82]);
        District::create(['id' => '595','name' => "Huyện Gò Công Tây",'city_id' =>82]);
        District::create(['id' => '596','name' => "Huyện Gò Công Đông",'city_id' =>82]);
        District::create(['id' => '597','name' => "Huyện Tân Phú Đông",'city_id' =>82]);
        District::create(['id' => '598','name' => "Thành phố Bến Tre",'city_id' =>83]);
        District::create(['id' => '599','name' => "Huyện Châu Thành",'city_id' =>83]);
        District::create(['id' => '600','name' => "Huyện Chợ Lách",'city_id' =>83]);
        District::create(['id' => '601','name' => "Huyện Mỏ Cày Nam",'city_id' =>83]);
        District::create(['id' => '602','name' => "Huyện Giồng Trôm",'city_id' =>83]);
        District::create(['id' => '603','name' => "Huyện Bình Đại",'city_id' =>83]);
        District::create(['id' => '604','name' => "Huyện Ba Tri",'city_id' =>83]);
        District::create(['id' => '605','name' => "Huyện Thạnh Phú",'city_id' =>83]);
        District::create(['id' => '606','name' => "Huyện Mỏ Cày Bắc",'city_id' =>83]);
        District::create(['id' => '607','name' => "Thành phố Trà Vinh",'city_id' =>84]);
        District::create(['id' => '608','name' => "Huyện Càng Long",'city_id' =>84]);
        District::create(['id' => '609','name' => "Huyện Cầu Kè",'city_id' =>84]);
        District::create(['id' => '610','name' => "Huyện Tiểu Cần",'city_id' =>84]);
        District::create(['id' => '611','name' => "Huyện Châu Thành",'city_id' =>84]);
        District::create(['id' => '612','name' => "Huyện Cầu Ngang",'city_id' =>84]);
        District::create(['id' => '613','name' => "Huyện Trà Cú",'city_id' =>84]);
        District::create(['id' => '614','name' => "Huyện Duyên Hải",'city_id' =>84]);
        District::create(['id' => '615','name' => "Thị xã Duyên Hải",'city_id' =>84]);
        District::create(['id' => '616','name' => "Thành phố Vĩnh Long",'city_id' =>86]);
        District::create(['id' => '617','name' => "Huyện Long Hồ",'city_id' =>86]);
        District::create(['id' => '618','name' => "Huyện Mang Thít",'city_id' =>86]);
        District::create(['id' => '619','name' => "Huyện  Vũng Liêm",'city_id' =>86]);
        District::create(['id' => '620','name' => "Huyện Tam Bình",'city_id' =>86]);
        District::create(['id' => '621','name' => "Thị xã Bình Minh",'city_id' =>86]);
        District::create(['id' => '622','name' => "Huyện Trà Ôn",'city_id' =>86]);
        District::create(['id' => '623','name' => "Huyện Bình Tân",'city_id' =>86]);
        District::create(['id' => '624','name' => "Thành phố Cao Lãnh",'city_id' =>87]);
        District::create(['id' => '625','name' => "Thành phố Sa Đéc",'city_id' =>87]);
        District::create(['id' => '626','name' => "Thành phố Hồng Ngự",'city_id' =>87]);
        District::create(['id' => '627','name' => "Huyện Tân Hồng",'city_id' =>87]);
        District::create(['id' => '628','name' => "Huyện Hồng Ngự",'city_id' =>87]);
        District::create(['id' => '629','name' => "Huyện Tam Nông",'city_id' =>87]);
        District::create(['id' => '630','name' => "Huyện Tháp Mười",'city_id' =>87]);
        District::create(['id' => '631','name' => "Huyện Cao Lãnh",'city_id' =>87]);
        District::create(['id' => '632','name' => "Huyện Thanh Bình",'city_id' =>87]);
        District::create(['id' => '633','name' => "Huyện Lấp Vò",'city_id' =>87]);
        District::create(['id' => '634','name' => "Huyện Lai Vung",'city_id' =>87]);
        District::create(['id' => '635','name' => "Huyện Châu Thành",'city_id' =>87]);
        District::create(['id' => '636','name' => "Thành phố Long Xuyên",'city_id' =>89]);
        District::create(['id' => '637','name' => "Thành phố Châu Đốc",'city_id' =>89]);
        District::create(['id' => '638','name' => "Huyện An Phú",'city_id' =>89]);
        District::create(['id' => '639','name' => "Thị xã Tân Châu",'city_id' =>89]);
        District::create(['id' => '640','name' => "Huyện Phú Tân",'city_id' =>89]);
        District::create(['id' => '641','name' => "Huyện Châu Phú",'city_id' =>89]);
        District::create(['id' => '642','name' => "Huyện Tịnh Biên",'city_id' =>89]);
        District::create(['id' => '643','name' => "Huyện Tri Tôn",'city_id' =>89]);
        District::create(['id' => '644','name' => "Huyện Châu Thành",'city_id' =>89]);
        District::create(['id' => '645','name' => "Huyện Chợ Mới",'city_id' =>89]);
        District::create(['id' => '646','name' => "Huyện Thoại Sơn",'city_id' =>89]);
        District::create(['id' => '647','name' => "Thành phố Rạch Giá",'city_id' =>91]);
        District::create(['id' => '648','name' => "Thành phố Hà Tiên",'city_id' =>91]);
        District::create(['id' => '649','name' => "Huyện Kiên Lương",'city_id' =>91]);
        District::create(['id' => '650','name' => "Huyện Hòn Đất",'city_id' =>91]);
        District::create(['id' => '651','name' => "Huyện Tân Hiệp",'city_id' =>91]);
        District::create(['id' => '652','name' => "Huyện Châu Thành",'city_id' =>91]);
        District::create(['id' => '653','name' => "Huyện Giồng Riềng",'city_id' =>91]);
        District::create(['id' => '654','name' => "Huyện Gò Quao",'city_id' =>91]);
        District::create(['id' => '655','name' => "Huyện An Biên",'city_id' =>91]);
        District::create(['id' => '656','name' => "Huyện An Minh",'city_id' =>91]);
        District::create(['id' => '657','name' => "Huyện Vĩnh Thuận",'city_id' =>91]);
        District::create(['id' => '658','name' => "Thành phố Phú Quốc",'city_id' =>91]);
        District::create(['id' => '659','name' => "Huyện Kiên Hải",'city_id' =>91]);
        District::create(['id' => '660','name' => "Huyện U Minh Thượng",'city_id' =>91]);
        District::create(['id' => '661','name' => "Huyện Giang Thành",'city_id' =>91]);
        District::create(['id' => '662','name' => "Quận Ninh Kiều",'city_id' =>92]);
        District::create(['id' => '663','name' => "Quận Ô Môn",'city_id' =>92]);
        District::create(['id' => '664','name' => "Quận Bình Thuỷ",'city_id' =>92]);
        District::create(['id' => '665','name' => "Quận Cái Răng",'city_id' =>92]);
        District::create(['id' => '666','name' => "Quận Thốt Nốt",'city_id' =>92]);
        District::create(['id' => '667','name' => "Huyện Vĩnh Thạnh",'city_id' =>92]);
        District::create(['id' => '668','name' => "Huyện Cờ Đỏ",'city_id' =>92]);
        District::create(['id' => '669','name' => "Huyện Phong Điền",'city_id' =>92]);
        District::create(['id' => '670','name' => "Huyện Thới Lai",'city_id' =>92]);
        District::create(['id' => '671','name' => "Thành phố Vị Thanh",'city_id' =>93]);
        District::create(['id' => '672','name' => "Thành phố Ngã Bảy",'city_id' =>93]);
        District::create(['id' => '673','name' => "Huyện Châu Thành A",'city_id' =>93]);
        District::create(['id' => '674','name' => "Huyện Châu Thành",'city_id' =>93]);
        District::create(['id' => '675','name' => "Huyện Phụng Hiệp",'city_id' =>93]);
        District::create(['id' => '676','name' => "Huyện Vị Thuỷ",'city_id' =>93]);
        District::create(['id' => '677','name' => "Huyện Long Mỹ",'city_id' =>93]);
        District::create(['id' => '678','name' => "Thị xã Long Mỹ",'city_id' =>93]);
        District::create(['id' => '679','name' => "Thành phố Sóc Trăng",'city_id' =>94]);
        District::create(['id' => '680','name' => "Huyện Châu Thành",'city_id' =>94]);
        District::create(['id' => '681','name' => "Huyện Kế Sách",'city_id' =>94]);
        District::create(['id' => '682','name' => "Huyện Mỹ Tú",'city_id' =>94]);
        District::create(['id' => '683','name' => "Huyện Cù Lao Dung",'city_id' =>94]);
        District::create(['id' => '684','name' => "Huyện Long Phú",'city_id' =>94]);
        District::create(['id' => '685','name' => "Huyện Mỹ Xuyên",'city_id' =>94]);
        District::create(['id' => '686','name' => "Thị xã Ngã Năm",'city_id' =>94]);
        District::create(['id' => '687','name' => "Huyện Thạnh Trị",'city_id' =>94]);
        District::create(['id' => '688','name' => "Thị xã Vĩnh Châu",'city_id' =>94]);
        District::create(['id' => '689','name' => "Huyện Trần Đề",'city_id' =>94]);
        District::create(['id' => '690','name' => "Thành phố Bạc Liêu",'city_id' =>95]);
        District::create(['id' => '691','name' => "Huyện Hồng Dân",'city_id' =>95]);
        District::create(['id' => '692','name' => "Huyện Phước Long",'city_id' =>95]);
        District::create(['id' => '693','name' => "Huyện Vĩnh Lợi",'city_id' =>95]);
        District::create(['id' => '694','name' => "Thị xã Giá Rai",'city_id' =>95]);
        District::create(['id' => '695','name' => "Huyện Đông Hải",'city_id' =>95]);
        District::create(['id' => '696','name' => "Huyện Hoà Bình",'city_id' =>95]);
        District::create(['id' => '697','name' => "Thành phố Cà Mau",'city_id' =>96]);
        District::create(['id' => '698','name' => "Huyện U Minh",'city_id' =>96]);
        District::create(['id' => '699','name' => "Huyện Thới Bình",'city_id' =>96]);
        District::create(['id' => '700','name' => "Huyện Trần Văn Thời",'city_id' =>96]);
        District::create(['id' => '701','name' => "Huyện Cái Nước",'city_id' =>96]);
        District::create(['id' => '702','name' => "Huyện Đầm Dơi",'city_id' =>96]);
        District::create(['id' => '703','name' => "Huyện Năm Căn",'city_id' =>96]);
        District::create(['id' => '704','name' => "Huyện Phú Tân",'city_id' =>96]);
        District::create(['id' => '705','name' => "Huyện Ngọc Hiển",'city_id' =>96]);
    }
}
